<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageCustomer.aspx.cs" Inherits="Admin_ManageCustomer" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:GridView ID="gvCustomer" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        onselectedindexchanged="gvCustomer_SelectedIndexChanged" 
    BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" 
    CellPadding="4" CellSpacing="2" ForeColor="Black">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="ID" Visible="False"></asp:BoundField>
            <asp:HyperLinkField DataTextField="name" HeaderText="Name"></asp:HyperLinkField>
            <asp:BoundField DataField="address" HeaderText="Address">
            <ItemStyle Width="80px" />
            </asp:BoundField>
            <asp:BoundField DataField="phone" HeaderText="Phone">
            <ItemStyle Width="150px" />
            </asp:BoundField>
            <asp:BoundField DataField="email" HeaderText="Email">
            </asp:BoundField>
            <asp:BoundField DataField="contact" HeaderText="Contact">
            </asp:BoundField>
            <asp:BoundField DataField="company" HeaderText="Company">
            <ItemStyle Width="100px" />
            </asp:BoundField>
        </Columns>
        <EditRowStyle Width="300px" />
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        

        
    </asp:GridView>

</asp:Content>

