<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageServiceOrder.aspx.cs" Inherits="Admin_ManageServiceOrder" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:GridView ID="gvServiceOrder" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        onselectedindexchanged="gvServiceOrder_SelectedIndexChanged" 
    BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" 
    CellPadding="4" CellSpacing="2" ForeColor="Black" EnableModelValidation="True" 
        onrowdeleting="gvServiceOrder_RowDeleting">
        <Columns>
            <asp:BoundField DataField="serviceorder" HeaderText="Name">
            <ItemStyle Width="100px" />
            </asp:BoundField>
            <asp:BoundField DataField="employee" HeaderText="Employee">
            <ItemStyle Width="80px" />
            </asp:BoundField>
            <asp:BoundField DataField="customer" HeaderText="Customer">
            <ItemStyle Width="150px" />
            </asp:BoundField>
            <asp:BoundField DataField="servicetype" HeaderText="Service type">
            <ItemStyle Width="100px" />
            </asp:BoundField>
            <asp:BoundField DataField="begindate" HeaderText="Begindate"></asp:BoundField>
            <asp:BoundField DataField="enddate" HeaderText="Enddate"></asp:BoundField>
            <asp:BoundField DataField="complete" HeaderText="Complete"></asp:BoundField>
            <asp:BoundField DataField="description" HeaderText="Description">
            </asp:BoundField>
        </Columns>
        <EditRowStyle Width="300px" />
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        
        
        
    </asp:GridView>

</asp:Content>

