<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ManageEmployee.aspx.cs" Inherits="Admin_ManageEmployee" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <asp:GridView ID="gvEmployee" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
        EnableModelValidation="True" 
        onselectedindexchanged="gvEmployee_SelectedIndexChanged" 
    BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" 
    CellPadding="3" GridLines="Horizontal">
        <Columns>
            <asp:BoundField DataField="id" HeaderText="ID">
            <ItemStyle Width="20px" />
            </asp:BoundField>
            <asp:BoundField DataField="name" HeaderText="Name">
            <ItemStyle Width="100px" />
            </asp:BoundField>
            <asp:BoundField DataField="role" HeaderText="Role">
            <ItemStyle Width="80px" />
            </asp:BoundField>
            <asp:BoundField DataField="address" HeaderText="Address">
            <ItemStyle Width="150px" />
            </asp:BoundField>
            <asp:BoundField DataField="username" HeaderText="User Name">
            <ItemStyle Width="100px" />
            </asp:BoundField>
        </Columns>
        <EditRowStyle Width="300px" />
        <FooterStyle BackColor="White" ForeColor="#000066" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        
    </asp:GridView>

</asp:Content>

